### ISSUE TITLE
Edit permissions

### ISSUE THREAD

**Issue by cinderblock** [willivolt/mathcamp-site#3]
Will, can you give me permissions to add others? I'd like to add another camper to add some things.

**Comment by willivolt** [comment]
@cinderblock , I don't think that I can do that on a personal account repository.  It looks like only the owner can invite collaborators. Let me know who you want added.

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository

**Comment by cinderblock** [comment]
Ah. Missed that.

Wanna just transfer them to me?

**Comment by willivolt** [comment]
@cinderblock We could do that. It might require also re-verifying the mathcamp.us domain ownership. I think that is tied to my account, not the repository. But that should just an update to a DNS TXT and CNAME record.

**Comment by cinderblock** [comment]
Please transfer to me. An org would cost yearly to maintain (to get the pages feature). We should be able to reverify the domain without much trouble. Is there a time we could do the transfer so that downtime is minimized if there are any DNS issues? Maybe tomorrow after work?

**Comment by cinderblock** [comment]
@willivolt Any thoughts on transfer? This feels like the right time of year to make any updates.

**Comment by willivolt** [comment]
I'll start the process today.  

In order for the HTTPS site to work, I think we will have to make two DNS updates.
I assume I will have change the CNAME record for www.mathcamp.us to cinderblock.github.io (current value: willivolt.github.io). Additionally, I I assume you will have to verify ownership, and it will give to a key that will have to go in a TXT record called _github-pages-challenge-cinderblock.  (there is currently a _github-pages-challenge-willivolt TXT record).

I currently have these both setup with 5 minute TTLs, so they shouldn't be getting cached for too long.

**Comment by willivolt** [comment]
Not sure when that last comment closed this.

**Comment by cinderblock** [comment]
I don't think I have any DNS access. Maybe that should be transferred as well? What are we using for DNS/registrar? I can transfer to Cloudflare - no markup registration + free DNS hosting.

**Comment by willivolt** [comment]
@cinderblock check you email.  I have added a user to my linode account that has edit dns permissions for mathcamp.us

**Comment by cinderblock** [comment]
Done

**Comment by willivolt** [comment]
The domain has been transferred to @cinderblock. He is free to also accept the transfer of this repo, create his own, or host it all elsewhere.

**Comment by cinderblock** [comment]
Can you transfer this repo to my GH account?

**Comment by willivolt** [comment]
@cinderblock I aborted the existing repo transfer and started a new one.
